In [1]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\justin wang\anaconda3\lib\site-packages (2.13.0)
Requirement already satisfied: tensorflow-intel==2.13.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow) (2.13.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.1.21 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.5.26)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (3.7.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (16.0.6)
Requirement already satisfied: numpy<=1.24.3,>=1.22 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.24.3)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (3.3.0)
Requirement already satisfied: packaging in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (4.24.0)
Requirement already satisfied: setuptools in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (68.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (2.3.0)
Requirement already satisfied: typing-extensions<4.6.0,>=3.6.6 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (4.5.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.57.0)
Requirement already satisfied: tensorboard<2.14,>=2.13 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (2.13.0)
Requirement already satisfied: tensorflow-estimator<2.14,>=2.13.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (2.13.0)
Requirement already satisfied: keras<2.14,>=2.13.1 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (2.13.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (0.31.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\justin wang\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.13.0->tensorflow) (0.38.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.22.0)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\justin wang\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.2.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\justin wang\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\justin wang\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\justin wang\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (4.9)
Requirement already satisfied: urllib3<2.0 in c:\users\justin wang\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (1.26.16)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\justin wang\anaconda3\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\justin wang\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\justin wang\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\justin wang\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\justin wang\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.1.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\justin wang\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\justin wang\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.2.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as sk
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu, sigmoid

In [22]:
dataChall = pd.read_csv("archive/Challenger_Ranked_Games.csv")
dataGM = pd.read_csv("archive/GrandMaster_Ranked_Games.csv")
dataM = pd.read_csv("archive/Master_Ranked_Games.csv")

In [23]:
data = pd.concat([dataChall, dataGM, dataM], axis=0)
data

,gameId,gameDuraton,blueWins,blueFirstBlood,blueFirstTower,blueFirstBaron,blueFirstDragon,blueFirstInhibitor,blueDragonKills,blueBaronKills,...,redAssist,redChampionDamageDealt,redTotalGold,redTotalMinionKills,redTotalLevel,redAvgLevel,redJungleMinionKills,redKillingSpree,redTotalHeal,redObjectDamageDealt
0,4247263043,1323,0,1,0,0,0,0,0,0,...,68,73016,49832,533,64,12.8,138,8,38711,60463
1,4247155821,1317,1,0,0,0,1,0,2,0,...,8,44218,37136,571,59,11.8,134,3,24829,14105
2,4243963257,932,0,0,0,0,0,0,0,0,...,20,30797,35364,400,50,10.0,89,5,12589,45201
3,4241678498,2098,0,0,0,1,1,0,1,1,...,72,125866,70528,832,84,16.8,205,9,65312,88202
4,4241538868,2344,1,1,1,1,1,1,2,2,...,83,131536,74596,794,85,17.0,227,7,86431,64141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107120,4216107910,2479,1,1,0,0,0,0,3,1,...,41,149798,72167,789,86,17.2,258,6,34890,62124
107121,4031558534,932,0,0,0,0,0,0,0,0,...,26,37534,32931,364,51,10.2,110,5,11983,31400
107122,3882136458,2081,0,1,1,0,0,0,1,0,...,68,97369,71576,797,85,17.0,222,8,33499,79612
107123,4137464714,1619,0,0,0,0,0,0,1,0,...,68,116262,59001,524,72,14.4,162,11,52292,60903
107124,4195660684,1129,1,0,1,0,0,1,1,0,...,4,33263,26963,423,47,9.4,71,1,12749,8035

In [24]:
results = data["blueWins"]
results

0         0
1         1
2         0
3         0
4         1
         ..
107120    1
107121    0
107122    0
107123    0
107124    1
Name: blueWins, Length: 199925, dtype: int64

In [25]:
data.drop(columns=["blueWins", "redWins", "redFirstTower", "redFirstBaron", "redFirstDragon", "redFirstInhibitor", "redFirstBlood"], inplace = True)
data

,gameId,gameDuraton,blueFirstBlood,blueFirstTower,blueFirstBaron,blueFirstDragon,blueFirstInhibitor,blueDragonKills,blueBaronKills,blueTowerKills,...,redAssist,redChampionDamageDealt,redTotalGold,redTotalMinionKills,redTotalLevel,redAvgLevel,redJungleMinionKills,redKillingSpree,redTotalHeal,redObjectDamageDealt
0,4247263043,1323,1,0,0,0,0,0,0,0,...,68,73016,49832,533,64,12.8,138,8,38711,60463
1,4247155821,1317,0,0,0,1,0,2,0,4,...,8,44218,37136,571,59,11.8,134,3,24829,14105
2,4243963257,932,0,0,0,0,0,0,0,0,...,20,30797,35364,400,50,10.0,89,5,12589,45201
3,4241678498,2098,0,0,1,1,0,1,1,2,...,72,125866,70528,832,84,16.8,205,9,65312,88202
4,4241538868,2344,1,1,1,1,1,2,2,11,...,83,131536,74596,794,85,17.0,227,7,86431,64141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107120,4216107910,2479,1,0,0,0,0,3,1,7,...,41,149798,72167,789,86,17.2,258,6,34890,62124
107121,4031558534,932,0,0,0,0,0,0,0,0,...,26,37534,32931,364,51,10.2,110,5,11983,31400
107122,3882136458,2081,1,1,0,0,0,1,0,6,...,68,97369,71576,797,85,17.0,222,8,33499,79612
107123,4137464714,1619,0,0,0,0,0,1,0,2,...,68,116262,59001,524,72,14.4,162,11,52292,60903
107124,4195660684,1129,0,1,0,0,1,1,0,6,...,4,33263,26963,423,47,9.4,71,1,12749,8035

In [26]:
data["dBaron"] = data["blueBaronKills"] - data["redBaronKills"]
data["dDragon"] = data["blueDragonKills"] - data["redDragonKills"]
data["dInhib"] = data["blueInhibitorKills"] - data["redInhibitorKills"]
data["dTower"] = data["blueTowerKills"] - data["redTowerKills"]
data["dWardPlace"] = data["blueWardPlaced"] - data["redWardPlaced"]
data["dWardKills"] = data["blueWardkills"] - data["redWardkills"]
data["dKills"] = data["blueKills"] - data["redKills"]
data["dKillingSpree"] = data["blueKillingSpree"] - data["redKillingSpree"]
data["dDamage"] = data["blueChampionDamageDealt"] - data["redChampionDamageDealt"]
data["dGold"] = data["blueTotalGold"] - data["redTotalGold"]
data["dCS"] = data["blueTotalMinionKills"] - data["redTotalMinionKills"]
data["dAvgLevel"] = data["blueAvgLevel"] - data["redAvgLevel"]
data["dJungleCS"] = data["blueJungleMinionKills"] - data["redJungleMinionKills"]
data["dHealing"] = data["blueTotalHeal"] - data["redTotalHeal"]

data.drop(columns=["blueBaronKills", "redBaronKills", "blueDragonKills", "redDragonKills", "blueInhibitorKills", "redInhibitorKills", "blueTowerKills",
                 "redTowerKills", "blueWardPlaced", "redWardPlaced", "blueWardkills", "redWardkills", "blueKills", "redKills", "blueKillingSpree",
                 "redKillingSpree", "blueChampionDamageDealt", "redChampionDamageDealt", "blueTotalGold", "redTotalGold", "blueTotalMinionKills",
                 "redTotalMinionKills", "blueAvgLevel", "redAvgLevel", "blueJungleMinionKills", "redJungleMinionKills", "blueTotalHeal", "redTotalHeal",
                  "blueDeath", "redDeath", "blueAssist", "redAssist", "blueTotalLevel", "redTotalLevel", "redObjectDamageDealt", "blueObjectDamageDealt"], inplace = True)
data

,gameId,gameDuraton,blueFirstBlood,blueFirstTower,blueFirstBaron,blueFirstDragon,blueFirstInhibitor,dBaron,dDragon,dInhib,...,dWardPlace,dWardKills,dKills,dKillingSpree,dDamage,dGold,dCS,dAvgLevel,dJungleCS,dHealing
0,4247263043,1323,1,0,0,0,0,0,-3,-1,...,-12,-4,-16,-4,-16977,-12831,-93,-1.6,-33,-7676
1,4247155821,1317,0,0,0,1,0,0,2,0,...,11,0,11,0,16025,3936,-40,0.8,-23,1568
2,4243963257,932,0,0,0,0,0,0,-2,-1,...,-12,-2,-15,-5,-6783,-12435,-94,-1.6,-25,-6022
3,4241678498,2098,0,0,1,1,0,0,-2,0,...,33,-17,-10,-6,-24259,-7081,-58,-0.8,21,-40594
4,4241538868,2344,1,1,1,1,1,1,-1,2,...,14,-8,-13,-2,3290,359,37,-0.4,25,-49270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107120,4216107910,2479,1,0,0,0,0,0,0,0,...,14,15,17,7,-7073,10299,14,0.6,-7,32606
107121,4031558534,932,0,0,0,0,0,0,-2,0,...,-11,-1,-18,-4,-11441,-9873,-36,-1.2,-31,1576
107122,3882136458,2081,1,1,0,0,0,-2,-3,-3,...,-18,4,-12,-1,-16726,-6143,-33,-1.4,-16,-2747
107123,4137464714,1619,0,0,0,0,0,-1,-1,-1,...,20,-18,-18,-7,-36209,-14321,-20,-2.4,-63,-35766
107124,4195660684,1129,0,1,0,0,1,0,0,1,...,4,1,11,2,15164,10640,3,2.0,47,9475